### ISSUE TITLE
[TODO] Implement new flag handling

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/MagicWE2#216]
**Description:**

Flags that can be used in commands, for example `-hollow`

Every action, shape and command may have different flags

---
TODO list:
- [ ] Come up with a simple, yet useful way to register flags
- [ ] Enable the command handling & suggestions
- [ ] Global / static edit flags? i.e. "always hollow" when editing
- [ ] Make sure brushes + brush ui still work
- [ ] Wiki
