### ISSUE TITLE
[TODO] BlockPalettes

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/MagicWE2#217]
**Description:**

Add block palettes and presets

These can be created from a selection or manually entered. Palettes save with the session and can be named. They also allow for use of `%` signs to define the relative percentage. 

Play together nicely with masks (#218)

---
TODO list:
- [x] Add palettes
- [x] Parse palettes
- [ ] Save / load palettes
- [x] Add weighted randomization (`%` sign) (Idea: `Palette::getBlocks() : \Generator` yields the block
- [x] Some kind of serialization
- [ ] UI
- [ ] Palette::swap to replace all palette entries with another, allowing for quicker //rotate and //flip?

**Comment by inxomnyaa** [comment]
Working code here https://github.com/thebigsmileXD/MagicWE2/tree/palette and here https://github.com/thebigsmileXD/MagicWE2/tree/palette-preview

**Comment by inxomnyaa** [comment]
Waiting for feedback. If you have twitter, please check https://twitter.com/XenialDan/status/1419723539654062094 and leave your ideas + feedback there

**Comment by inxomnyaa** [comment]
Current progress
![image](https://user-images.githubusercontent.com/8733998/135699660-ed60259d-eb94-4780-b8b6-f65eee9c81b9.png)
![image](https://user-images.githubusercontent.com/8733998/135699661-1227991d-d9fa-468c-9e29-32435136d74b.png)
![image](https://user-images.githubusercontent.com/8733998/135699663-32148db7-4352-41c5-b98e-e70caa551d87.png)
