### ISSUE TITLE
[TODO] Masks

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/MagicWE2#218]
**Description:**

See https://github.com/Brennian/Arceon/wiki/Masks

Masks basically are selection modifiers which change which blocks get iterated in (Async)Action::execute()

Might be useful for placing snow layers

They may also include noise algorythms

---
TODO list:
- [ ] Figure out a syntax (probably add secondary parameter `mask` to //set, //replace etc)
- [ ] Implement masks globally (plugins + users can use it via API)
- [ ] Serialization
- [ ] Modify actions' outcome
- [ ] Mask extends CustomShape?
