### ISSUE TITLE
[TODO] Add assets

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/MagicWE2#221]
**Description:**
See [this video](https://www.youtube.com/watch?v=JhbEYIhG2UM). Clipboard brush matches it best. Will hold structures, schematics and exported clipboards

This needs to be finished before #217 can be added, thus [milestone is 10.1.4](https://github.com/thebigsmileXD/MagicWE2/milestone/8)
---
TODO list:
- [x] Add asset store
- [ ] Allow automatic rotation depending on player's facing
- [x] Display outline
- [ ] Command blocks and structure blocks display floating name, might place one in the corner
- [ ] Maybe display block preview using minecarts/falling blocks as seen in https://twitter.com/XenialDan/status/1341913532284207105
- [x] Clipboards can be saved as assets
- [x] UI is similar to session brush, utilizing InvMenu double chest
- ~Display block is most common block (except air), enchanted, MWE2 nbt tag, lore contains string representation of blocks~ This is planned for palette instead. Using scaffolding instead.
- [x] Upon creation/load, open UI which allows changing the asset name _(optional: and block filter / override blocks toggle?)_ and shows size, origin (file format)
- [ ] Abort placement by switching to another item
- [ ] Enable export to clipboard, structure block and schematic
- [x] Replace clipboard brush with asset brush
- [ ] Global assets & private assets

**Comment by inxomnyaa** [comment]
![image](https://user-images.githubusercontent.com/8733998/107843292-4564fe00-6dca-11eb-8cf0-27d443ca1146.png)
![image](https://user-images.githubusercontent.com/8733998/107863173-49d4f980-6e52-11eb-8daa-c31b65aca976.png)
![image](https://user-images.githubusercontent.com/8733998/108577572-d59ec800-7321-11eb-8bcf-09def1c0467b.png)
![image](https://user-images.githubusercontent.com/8733998/108587631-16640480-7355-11eb-8f53-d294acc41d41.png)

**Comment by inxomnyaa** [comment]
https://youtu.be/Lmf4pw8SDsc
