### ISSUE TITLE
[TODO] Extract BlockState parsing into virion

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/MagicWE2#236]
**Description:**
Currently [libstructure](https://github.com/thebigsmileXD/libstructure) still depends on MagicWE2. This should be changed to allow use of the library in other projects.

This would also ease maintainability in MWE2 & the BlockState parsing.

The repo is currently already present [here](https://github.com/thebigsmileXD/libblockstate), but without any of the PM code.

---
TODO list:
- [x] Create virion
- [x] Use virion in MagicWE2
- [ ] Make libstructure depend on this virion (if possible)
- [ ] Rewrite some of the stuff

**Comment by inxomnyaa** [comment]
libblockstate is mostly finalized
