### ISSUE TITLE
[TODO] Reimplement //rotate and //flip

### ISSUE THREAD

**Issue by inxomnyaa** [thebigsmileXD/MagicWE2#252]
**Description:**
Due to extracting blockstates into a virion (see #236), the rotate and flip method had to be removed to loosen up the dependency on MWE2.

I have already added `API::rotate()` in this branch: [flip-rotate](https://github.com/thebigsmileXD/MagicWE2/tree/experiment/flip-rotate). As of now it only supports changing the block positions, not the states though.

---
**TODO list:**
- [ ] Implement blockstate modifications
- [ ] Implement flip
- [ ] Correct counterclockwise => clockwise
- [ ] Update rotation and flip data json
- [ ] Implement rotating around origin/center
- [ ] Correct pasting in new chunks not working
- [ ] Allow -90 as rotation degrees parameter as synonym for 270
- [ ] Fix Rotate- & FlipAction not updating progress / calculating changed count
- [ ] Remove unnecessary try-catch blocks
- [ ] Allow rotating .mcstructure files
